### ISSUE TITLE
[Feature 👩‍💻] 개발 환경 설정 및 패키지 구조 설계

### ISSUE THREAD

**Issue by yu-heejin** [travity-team/travity-app#1]
## Description ✏️
* React Native 개발을 위한 개발 환경 설정 및 패키지 구조 설계

## TODO
- [x] 개발 환경 구축
- [x] 패키지 구조 설계
- [x] prettier, eslint 설정하기
- [x] node version 설정하기
- [x] gitignore 설정하기
