### ISSUE TITLE
[Feature 👩‍💻] 배포, 개발 환경 분리

### ISSUE THREAD

**Issue by yu-heejin** [travity-team/travity-app#8]
## Description ✏️
* axios 세팅 및 배포, 개발 환경 분리

## TODO
- [x] axios.create 설정하기
- [x] 배포, 개발, 스테이징 환경 분리하기
- [ ] module alias 설정
- [x] react-native-config 적용
- [ ] storybook과 app 분리하기
